### ISSUE TITLE
variable Date for Subject

### ISSUE THREAD

**Issue by ChrigiGee** [tomaszkrajewski/tb-subswitch#11]
Hi and Good evening,

I like your PlugIn really, and i like to test the Beta too.
I like to use with Variables, your PlugIn.

Likewise, I use to until now [PRIV: {number:NN}] [Datum: {date:yyyy/mm/dd}]

Today I see it's no more work. I hope you can check its other Installation too or only me.
This evening, I update the Beta from August to the Beta of November.

![2024-11-12 19 44 14](https://github.com/user-attachments/assets/7703b30b-2334-4f26-9db5-c35edbe4f471)

Kind regards
Chris

**Comment by ChrigiGee** [comment]
Hi Tom,

> indded, dates are not working SubSwitch. Planned to be fixed in the next increment

Thanks a lot and sorry if it is like annoying you.

Chris

**Comment by tomaszkrajewski** [comment]
Solved in 1.0.5. Package avaiable in https://github.com/tomaszkrajewski/tb-subswitch/releases/download/1.0.5/subjects_prefix_switch_1.0.5.xpi. Soon it will be officially via addons.thunderbird

**Comment by tomaszkrajewski** [comment]
Solved in 1.0.5. Package avaiable in https://github.com/tomaszkrajewski/tb-subswitch/releases/download/1.0.5/subjects_prefix_switch_1.0.5.xpi. Soon it will be officially via addons.thunderbird
