### ISSUE TITLE
Subswitch not savings changes or additions

### ISSUE THREAD

**Issue by Headbanger64** [tomaszkrajewski/tb-subswitch#3]
Subswitch won't save changes or additions to the prefixes.
I can add a new Prefix at the Prefixes Option, but after I close the Option window, the entry doesn't appear in the Subject drop down menu. I then go back to the Prefix Options and I see that the latest addition doesn't appear in the Options window.
The problem began on Thunderbird 64 bit Update/Upgrade 91.4.0.  I've since updated to *4.1 and the problem persists.

**Comment by tomaszkrajewski** [comment]
... cannot reproduce :/ could you please drop some more details? is it every case? are you confirming that you saved the modified config? windows or linux ? could you please make a few screens or drop a short video with the failing scenario?
thanks 

tk

**Comment by tomaszkrajewski** [comment]
Kind reminder....

**Comment by Headbanger64** [comment]
Fixed it. I just uninstalled, then reinstalled.




    On Monday, January 3, 2022, 05:00:06 AM PST, tomaszkrajewski ***@***.***> wrote:  
 
 


Kind reminder....

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tomaszkrajewski** [comment]
as stated - fixed
