### ISSUE TITLE
[Localisation] Prefix

### ISSUE THREAD

**Issue by 121sim** [tomaszkrajewski/tb-subswitch#4]
Hi & thanks for your past work.

A small issue with localisation, like [Prévi] become [PrÃ©vi] when detecting a new prefix.

Thanks.

**Comment by tomaszkrajewski** [comment]
Hi, by design it wasn't foreseen to support/operate on country/language specific letters. Only pure latin alphabet. I even wonder if  it was possible to use national characters in 2008 when SubSwitch was developed.
No resources now to proceed with such change :(
