### ISSUE TITLE
[Enhancement] Right-click menu

### ISSUE THREAD

**Issue by 121sim** [tomaszkrajewski/tb-subswitch#5]
Hi again,

if this project is still active, here is a suggestion : when editing a message, and right-clicking for misspelled word, Subswitch comes first, it could come after the suggested words.

Thanks.

![Subswitch](https://github.com/tomaszkrajewski/tb-subswitch/assets/74899182/180588fd-5be1-4c0c-8552-a0d327d79360)

**Comment by tomaszkrajewski** [comment]
I'll change it in next version (compatibility only with TB 115)

**Comment by 121sim** [comment]
Great.

**Comment by tomaszkrajewski** [comment]
In the version compatiblem with TB >= 128 (webextension style) the position of right-click menu is in the end of the list. It's managed by TB, not extension.
